databases:
  - name: hassatubeauty
    databaseName: hassatubeauty
    user: hassatubeauty

services:
  - type: web
    name: hassatubeauty
    env: ruby
    buildCommand: "./api/bin/render-build.sh"
    startCommand: "cd api && bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hassatubeauty
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false